

spring:
  application:
    name: EmailNotificationMicroservice
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: product-created-events
      properties:
        spring-json-trusted-packages: com.appsdeveloperblog.ws.products
        schema-registry-url: http://localhost:8081
        specific-avro-reader: true
    producer: #for Dead Letter Topic
      bootstrap-servers: localhost:9092, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8082